#
# This source file is part of the Apodini HotROD example open source project
#
# SPDX-FileCopyrightText: 2022 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  logging:
    logLevel: debug

  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true


service:
  pipelines:
    traces:
      receivers: otlp
      exporters: [logging, jaeger]
